syntax = "proto3";

import "google/api/annotations.proto";

package example;

option java_package = "io.vertx.example.grpc";
option java_multiple_files = true;

service ExampleService {
  rpc Unary(Request) returns (Response) {
    option (google.api.http) = {
      get: "/v1/example/unary/{value}"
    };
  }
  rpc ServerStreaming(Request) returns (stream Response) {
    option (google.api.http) = {
      get: "/v1/example/serverstreaming/{value}"
    };
  };
  rpc ClientStreaming(stream Request) returns (Response);
  rpc BidiStreaming(stream Request) returns (stream Response);
}

message Request {
  string value = 1;
}

message Response {
  string value = 1;
}
