= Vert.x 3.0 Simple Maven Verticle project

This project is very similar to the maven-simplest project but instead of embedding Vert.x it shows an example
of writing the code as a verticle.

You can run it directly in your IDE by creating a run configuration that uses the main class `io.vertx.core.Starter`
and passes in the arguments `run io.vertx.example.HelloWorldVerticle`.

The pom.xml uses the Maven shade plugin to assemble the application and all it's dependencies into a single "fat" jar.

To build a "fat jar"

    mvn package

To run the fat jar:

    java -jar target/maven-verticle-3.0.0-SNAPSHOT-fat.jar

(You can take that jar and run it anywhere there is a Java 8+ JDK. It contains all the dependencies it needs so you
don't need to install Vert.x on the target machine).

Now point your browser at http://localhost:8080

Writing code in verticles allow you to scale it more easily, e.g. let's say you have 8 cores on your server and you
want to utilise them all, you can deploy 8 instances as follows:

    java -jar target/maven-verticle-3.0.0-SNAPSHOT-fat.jar -instances 8

You can also enable clustering and ha at the command line, e.g.

    java -jar target/maven-verticle-3.0.0-SNAPSHOT-fat.jar -cluster

    java -jar target/maven-verticle-3.0.0-SNAPSHOT-fat.jar -ha

Please see the docs for a full list of Vert.x command line options.

### Other examples

This project contains some other example:

#### Hello Configuration Verticle

This link:core-examples/src/main/java/io/vertx/example/HelloConfigurableVerticle.java[] retrieves the configuration
passed into the command line. Once built you can launch it as follows:


    # Return `Hello World` as no configuration provided
    vertx run io.vertx.example.HelloConfigurableVerticle -cp  /application/target/maven-verticle-3.0.0-SNAPSHOT.jar

    # Return `Hello Vert.x`
    vertx run io.vertx.example.HelloConfigurableVerticle -cp  /application/target/maven-verticle-3.0.0-SNAPSHOT.jar
    -conf src/conf/my-conf.json


