= Vert.x Metrics Examples

Vert.x core provides a Service Provide Interface (SPI) for collecting metrics. The Dropwizard implementation
collects these metrics in a Dropwizard registry that can be used for reporting in other system or can
be queried via the Dropwizard MetricsService.

== UI monitoring dashboard

This example is a UI monitoring dashboard built on top of the Dropwizard metrics implementation.

The link:src/main/java/io/vertx/example/metrics/dashboard/[Java monitoring dashboard example]

The dashboard uses the vertx-web eventbus bridge to push metrics periodically on the event bus.
The metrics are retrieved from the MetricsService in Json format.

Run the dashboard in your IDE, then open your browser and hit link:http://localhost:8080 to see the dashboard

To enable JMX append the following options: `-Dvertx.metrics.options.jmxEnabled=true -Dvertx.metrics.options.jmxDomain=vertx`.
Then, if you open a JMX explorer (such the JConsole), in the list of beans you will find the Vert.x metrics under the
`vertx` domain.

If you want to use Jolokia to expose the JMX metrics as a REST interface, download the Jolokia JVM agent from https://jolokia.org/download.html and create a `JAVA_OPTS` env variable as follow:

----
export JAVA_OPTS="-javaagent:path/to/jolokia-jvm-x.x.x-agent.jar=port=7777,host=localhost"
----

Once defined, relaunch the application with the JMX metrics enabled.
