= Vert.x examples

This repository contains a range of examples so you can get up and running easily with Vert.x.

== Maven users

Start with the link:maven-simplest[simplest Maven example] to show you how to setup a simple Vert.x project that uses
Maven. You need to have Java 8 installed and set the `JAVA_HOME` environment variable to point to your Java 8
installation.

Use that as a template for setting up a Maven project with Vert.x.

Progress to the link:maven-verticles/maven-verticle[simple Maven verticle example] to show you how to deploy your code as verticles in a Maven project. Also check link:maven-verticles[Maven verticles examples] to show how you can use Maven with Groovy, Ruby, and JavaScript verticles.

Want to start right away, open the first example in Eclipse Che:

image:http://beta.codenvy.com/factory/resources/codenvy-contribute.svg["Open workspace in Eclipse Che", link="http://beta.codenvy.com/f?id=9skz1321dxbqpj5j"]

== Gradle users

Start with the link:gradle-simplest[simplest Gradle example] to show you how to setup a simple Vert.x project that uses Gradle.

Use that as a template for setting up a Gradle project with Vert.x.

Progress to the link:gradle-verticles[simple Gradle verticle example] to show you how to deploy your code as verticles in
a Gradle project

== Neither Maven nor Gradle users

That's fine too :)

You can run most of the examples at the command line using `vertx run` if you have Vert.x installed (see below).


== Some examples need examples-utils

You may find examples that need examples-utils. You need to build it from link:examples-utils:

```
git clone https://github.com/vert-x3/vertx-examples.git
cd vertx-examples
cd examples-utils
mvn clean install
```

== The examples

The examples demonstrate how to use all different bits of Vert.x including Vert.x core, Vert.x-Web and various other
services and features.

Most of the examples have been written as verticles. For more information on verticles please consult the Vert.x core manual.

Using verticles allows you to scale and run your code from the command line more easily, but if you prefer the same code in the verticles can also be run embedded. It's really up to you. Verticles are
entirely optional in Vert.x.

== Different languages

Most of the examples are available in all the languages that Vert.x supports.

You'll find the examples for the relevant language in a directory `src/main/${lang}` where `lang` is an identifier for the
 language, e.g. `java`, `js`, `ruby` etc.

For example you'll find the Vert.x core Java examples in link:core-examples/src/main/java[] and you'll find the Vert.x core
JavaScript examples in link:core-examples/src/main/js[]

NOTE: All the non-Java examples are automatically generated from the Java examples using our magic code translator.

=== Running the examples

==== Running in your IDE

Most of the Java examples can be run directly in your IDE (if you have one!).

We provide a `main()` method in most of the example classes which allows you to conveniently run them directly in your IDE.

Just right click the main method or class in your IDE and run as... application (supported by all major IDEs).

==== Running at the command line

If `vertx` is installed you can also run any verticle directly on the command line. This way of working may be of interest
to you, if you don't want to use Maven or Gradle or perhaps you don't use an IDE.

Or perhaps you're just a command line kind of person.

If you're coming from using other platforms such as Node.js you might want to work this way. You can think of the
`vertx` command as a bit like the `node` command in Node.js.

Instructions for installing Vert.x are in the next section.

Once Vert.x is installed, to run an example, just cd to the example directory and type `vertx run` followed by the filename
of the verticle. For example

----
cd core-examples/src/main/java/io/vertx/example/core
vertx run EchoServer.java

cd core-examples/src/main/js/echo
vertx run echo_server.js
----

Yes! You can run *Java source files* directly using Vert.x (no compilation required).

==== Installing Vert.x

NOTE: This is only necessary if you want to run Vert.x at the command line. If you'd prefer to work with Maven or
Gradle projects then you don't need to pre-install Vert.x - you just let Maven/Gradle pull in the Vert.x dependencies
into your project as you would with any dependency.

Pre-requisites: You will need to have Java 8 JDK installed.

1. Download a link:https://bintray.com/vertx/downloads/distribution/view[Vert.x 3 distribution]
2. Unzip it somewhere on your disk (e.g. in your home directory)
3. Set your `PATH` environment variable to include the installation directory
4. Test the install by typing `vertx -version`.

On the download page, you will find several _distributions_. Each distribution has a different set
 of components:

* **Min**: The _min_ distribution contains only Vert.x Core, the support of the different
 languages, and the Hazelcast clustering.
* **Full**: The _full_ distribution contains all the components of the Vert.x stack. It includes
 Vert.x web and the different data access technologies.

=== Vert.x core examples

The link:core-examples/README.adoc[Vert.x core examples] contains a wide range of examples using just Vert.x Core.

=== Vert.x-Web examples

Vert.x-Web is a toolkit for building web applications using Vert.x

The link:web-examples/README.adoc[Vert.x-Web examples] contains a wide range of examples using Vert.x-Web

=== Vert.x Web Client examples

Vert.x Web Client that provides an easy to use web client for Vert.x.

The link:web-client-examples/README.adoc[Vert.x Web Client examples] contains a wide range of examples using the Vert.x Web Client

=== Vertx Unit examples

Vertx-Unit is a library for writing asynchronous tests. We include some examples of how to use this tool to test
your Vert.x (or other asynchronous) applications.

The link:unit-examples/README.adoc[Vert.x Unit examples] shows how to use Vert.x Unit.

=== Vert.x JUnit 5 examples

The `vertx-junit5` modules allow testing Vert.x asynchronous operations with JUnit 5.

See link:junit5-examples/README.adoc[Vert.x JUnit 5 examples].

=== RxJava examples

Vert.x for RxJava provides most of its APIs as RxJava so you can use those if you prefer.

RxJava is a great choice when you want to perform complex operations on multiple asynchronous streams of data.

The link:rxjava-2-examples/README.adoc[Vert.x RxJava 2] / link:rxjava-1-examples/README.adoc[Vert.x RxJava 1] examples contains a wide range of examples using Vert.x for RxJava

=== gRPC examples

The link:grpc-examples/README.adoc[Vert.x gRPC Examples] show how you can implement a gRPC service and invoke a gRPC service with Vert.x.

=== Kotlin examples

The link:kotlin-examples/README.adoc[Vert.x Kotlin Examples] shows a few examples with Kotlin such a REST application,
Kotlin coroutines and usage of https://github.com/kotlintest/kotlintest[KotlinTest].

=== Mail examples

The link:mail-examples/README.adoc[Vert.x Mail examples]
contains a few examples using Vert.x Mail

The mail examples show different ways to create the mail message and send it via
tls, ssl etc. The examples either use `localhost:25` to send a mail or use host
`mail.example.com`. To actually run the examples you will have to change the
mail server and the user credentials in the `MailLogin` example.

=== Maven Service Factory examples

The link:maven-service-factory-examples/README.adoc[Vert.x Maven service factory examples] shows how to package a verticle that
can be deployed using the Maven Service Factory. Such a deployment is also demonstrated using either the command line
or the api.

=== Service Proxy Examples

The link:service-proxy-examples/README.adoc[Vert.x Service Proxy examples] contains an example of service proxy usage.
It depicts how a service provider can be implemented and how the published service can be consumed.

=== Docker examples

The link:docker-examples/README.adoc[Vert.x Docker examples] shows how to deploy Vert.x application in Docker containers.
It also contains an example of the application that can be deployed on Fabric8.

=== Spring Examples

The link:spring-examples/README.adoc[Vert.x Spring Examples] shows how vert.x application can be integrated inside a Spring
ecosystem.

=== Redis example

The link:redis-examples/README.adoc[Vert.x Redis Example] shows how you can interact with Redis using the vert.x Redis client.

=== Mongo example

The link:mongo-examples/README.adoc[Vert.x Mongo Example] shows how you can interact with MongoDB using the vert.x Mongo client.

=== Reactive SQL client example

The link:reactive-sql-client-examples/README.adoc[Reactive SQL Client Examples] shows how you can interact PostgreSQL or MySQL Databases using the Reactive SQL client.

=== JDBC example

The link:jdbc-examples/README.adoc[Vert.x JDBC Examples] shows how you can interact JDBC Databases using the vert.x JDBC
client.

=== Kafka example

The link:kafka-examples/README.adoc[Vert.x Kafka Examples] shows how you can interact Kafka using the vert.x Kafka
client.

=== MQTT example

The link:mqtt-examples/README.adoc[Vert.x MQTT Examples] shows how you can write MQTT servers and clients using Vert.x MQTT.

==== Service Proxy Examples

The link:service-proxy-examples/README.adoc[Vert.x Service Proxy examples] contains an example of service proxy usage.
It depicts how a service provider can be implemented and how the published service can be consumed.

=== AMQP Bridge examples

The link:amqp-bridge-examples/README.adoc[Vert.x AMQP Bridge Examples] show how you can interact with AMQP 1.0 servers using the Vert.x AMQP Bridge.

=== Java 9 examples

This link:java9-examples/README.adoc[Java 9 examples] shows how a simple Java 9 modular application using Vert.x as anonymous modules.

=== Vert.x fatjar examples

The link:fatjar-examples/README.adoc[Vert.x fatjar Examples] show how you can build fatjar with Maven or Gradle.

=== HTTP/2 Showcase

This link:http2-showcase/README.md[HTTP/2 Showcase] application highlights the benefits of HTTP/2 when dealing with latency on the web.

=== Camel Bridge examples

The link:camel-bridge-examples/README.adoc[Vert.x Camel Bridge Examples] show how you can use Apache Camel routes from
the event bus.

=== JCA example

The link:jca-examples/README.adoc[Vert.x JCA Examples] provide a JEE compliant application that enables to you deploy the application into a
 link:http://wildfly.org[Wildfly] application server. While simple in implementation, the JCA examples
 provides a good point of departure for your own development.

=== Micrometer metrics examples

The link:micrometer-metrics-examples/README.adoc[Vert.x Micrometer metrics examples] show how to collect Vert.x metrics
with link:https://micrometer.io/[Micrometer] and send them to backends such as Prometheus or InfluxDB.

=== GraphQL examples

The link:web-graphql-examples/README.adoc[Vert.x Web GraphQL] examples contain simple client/server GraphQL applications built with https://vertx.io/docs/vertx-web-graphql/java/[Vert.x Web GraphQL] and the https://www.graphql-java.com/[GraphQL-Java] library.
