= Vert.x core examples

Here you will find examples demonstrating Vert.x core in action.

Vert.x core provides fairly low level functionality for a diverse range of functions including HTTP, TCP, UDP,
WebSockets, file system access, timers, verticles and more. Please consult the Vert.x core manual for detailed
documentation on Vert.x core.

== Dependencies required

To use Vert.x core in your own Maven or Gradle project add the following dependency

----
Group ID: io.vertx
Artifact ID: vertx-core
----

== Embedding

Vert.x core can be embedded in any Java class and run that way if you like.

The link:src/main/java/io/vertx/example/core/embed/EmbeddedServer.java[Java embedded example] shows an example of that.
Just right click the class in your IDE to run it directly.

== Net examples

These examples demonstrate usage of Vert.x net servers and clients - these are used for TCP (and SSL) servers and clients.

=== Echo

This example consists of an echo server verticle which serves TCP connections, and simply echoes back on the connection
whatever it receives.

You can run the echo server then run `telnet localhost 1234` from a console to connect to it. Type some stuff and see it
echoed back to you.

It also contains an echo client, which creates a connection to the server, sends some data and logs out what it receives
back. You can use that as an alternative to connecting via telnet.

link:src/main/java/io/vertx/example/core/net/echo/Server.java[Java echo server]
link:src/main/java/io/vertx/example/core/net/echo/Client.java[Java echo client]

link:src/main/js/io/vertx/example/core/net/echo/server.js[JavaScript echo server]
link:src/main/js/io/vertx/example/core/net/echo/client.js[JavaScript echo client]

=== Echo SSL

This is the same as the Echo example but using SSL to encrypt connections

link:src/main/java/io/vertx/example/core/net/echossl/Server.java[Java echo ssl server]
link:src/main/java/io/vertx/example/core/net/echossl/Client.java[Java echo ssl client]

link:src/main/js/io/vertx/example/core/net/echossl/server.js[JavaScript echo ssl server]
link:src/main/js/io/vertx/example/core/net/echossl/client.js[JavaScript echo ssl client]

== HTTP examples

These examples demonstrate usage of HTTP with Vert.x.

=== Simple

A very simple HTTP server which always responds with the same response:

link:src/main/java/io/vertx/example/core/http/simple/Server.java[Java simple HTTP server]

You can run the server then open a browser and point it at link:http://localhost:8080[]

And a simple HTTP client which makes a request to the server.

link:src/main/java/io/vertx/example/core/http/simple/Client.java[Java simple HTTP client]

=== HTTPS

Like the simple example, but using HTTPS instead of HTTP

link:src/main/java/io/vertx/example/core/http/https/Server.java[Java simple HTTPS server]

You can run the server then open a browser and point it at link:http://localhost:4443[]

And a simple HTTPS client which makes a request to the server.

link:src/main/java/io/vertx/example/core/http/https/Client.java[Java simple HTTPS client]

=== Proxy

A simple toy HTTP proxy. The proxy receives requests and forwards them to the endpoint server, it also takes responses
from the other server and passes them back to the client.

link:src/main/java/io/vertx/example/core/http/proxy/Server.java[The Java endpoint server]
link:src/main/java/io/vertx/example/core/http/proxy/Proxy.java[The Java proxy]
link:src/main/java/io/vertx/example/core/http/proxy/Client.java[The client]

=== Sendfile

This example demonstrates how you can serve static files from disk using a Vert.x http server.

link:src/main/java/io/vertx/example/core/http/sendfile/SendFile.java[Java static file server example]

You can run the server then open a browser and point it at link:http://localhost:8080[]

NOTE: In practice you would probably actually use Vert.x-Web for this rather than writing a web server at this low level. Serving
files manually like this can leave you open to security exploits, e.g. by clients crafting URI paths which try to access
resources outside of the permitted area. Vert.x-Web provides URI path normalisation to avoid these kinds of exploits and comes
with a static file handler which also handles caching headers and other features that you would probably want when serving
static files in a web application.

=== Simple form

This example demonstrates how you can handle an HTML form on the server.

link:src/main/java/io/vertx/example/core/http/simpleform/SimpleFormServer.java[Java simple form server example]

You can run the server then open a browser and point it at link:http://localhost:8080[]

NOTE: In practice you would probably also use Vert.x-Web for this rather than writing a server at this low level. Vert.x-Web
provides built in support for HTML forms, and avoids some of the security issues due to maliciously crafted URI paths.

=== Simple form file upload

This example demonstrates how you can handle file uploads from an HTML form submission.

link:src/main/java/io/vertx/example/core/http/simpleformupload/SimpleFormUploadServer.java[Java simple form file upload server example]

You can run the server then open a browser and point it at link:http://localhost:8080[]

NOTE: In practice you would probably also use Vert.x-Web for this rather than writing a server at this low level. Vert.x-Web
provides built in support for HTML forms and file uploads, and avoids some of the security issues due to maliciously
crafted URI paths.

=== Http request body upload

This examples demonstrates an HTTP server receiving a request and pumping the request body to a file on disk without
ever storing the entire request body fully in memory.

There's also a client which sends a request to the server and pumps a file from disk to the HTTP request body. The file
is uploaded successfully even if the file is very large (GigaBytes).

link:src/main/java/io/vertx/example/core/http/upload/Server.java[Java upload server example]
link:src/main/java/io/vertx/example/core/http/upload/Client.java[Java upload client example]

=== HTTP Server Sharing

A server that illustrates the round robin orchestrated by vert.x when several verticles are opening HTTP servers on the same port:

link:src/main/java/io/vertx/example/core/http/sharing/Server.java[Server Launcher]

link:src/main/java/io/vertx/example/core/http/sharing/HttpServerVerticle.java[HTTP Server Verticle]

The `Server` deploys two instances of the `HttpServerVerticle` verticle.

You can run the server then open a browser and point it at link:http://localhost:8080[]. Requests will be handled by an instance after the other.

The `Client` illustrates the round robin by periodically requesting the server and displays the response content.

link:src/main/java/io/vertx/example/core/http/sharing/Client.java[Java simple HTTP client]

You can directly launch the `HTTPServerVerticle` using the `vertx run` command. Then you can set the number of instance you want:

```
vertx run io.vertx.example.core.http.sharing.HttpServerVerticle -instances 4
```

=== WebSockets echo example

This example shows a Vert.x HTTP server which handles websockets connections. This example simply echoes back to the client
whatever it receives on the websocket.

There's also a client which connects to the server, sends some data and logs out what it receives.

link:src/main/java/io/vertx/example/core/http/websockets/Server.java[Java WebSockets server example]
link:src/main/java/io/vertx/example/core/http/websockets/Client.java[Java WebSockets client example]

link:src/main/java/io/vertx/example/core/http/websockets/ws.html[Javascript WebSockets client example]

You can run the server then open a browser and point it at link:http://localhost:8080[]

NOTE: in practice you would probably use Vert.x-Web to build a web application that uses WebSockets

== Event bus examples

These examples demonstrate usage of the event bus in Vert.x

=== Point to point

This example demonstrates point to point messaging between a receiver and a sender.

The receiver listens on an address on the event bus for incoming messages. When it receives a message it replies to it.

The sender sends a message to that address every second, when it receives a reply it logs it.

link:src/main/java/io/vertx/example/core/eventbus/pointtopoint/Receiver.java[Java event bus receiver]
link:src/main/java/io/vertx/example/core/eventbus/pointtopoint/Sender.java[Java event bus sender]

You can run the Java sender and receiver in your IDE or at the command line.

At the command line you should run Sender and Receiver in different consoles using the `-cluster` flag:

----
vertx run Receiver.java -cluster

vertx run Sender.java -cluster
----

The `-cluster` flag allows different Vert.x instances on the network to cluster the event bus together into a single
event bus.

=== Publish / Subscribe

This example demonstrates publish / subscribe messaging between a receivers and a sender. With pub/sub messaging
you can have multiple subscribers who all receive messages from publishers.

A receiver listens on an address on the event bus for incoming messages. When it receives a message it logs it.

The sender sends a message to that address every second, when it receives a reply it logs it.

link:src/main/java/io/vertx/example/core/eventbus/pubsub/Receiver.java[Java event bus pubsub receiver]
link:src/main/java/io/vertx/example/core/eventbus/pubsub/Sender.java[Java event bus pubsub sender]

You can start as many senders or receivers as you like in your IDE or at the command line.

At the command line you should run Sender and Receiver in different consoles using the `-cluster` flag:

----
vertx run Receiver.java -cluster

vertx run Sender.java -cluster
----

The `-cluster` flag allows different Vert.x instances on the network to cluster the event bus together into a single
event bus.

== Verticle examples

These examples show verticles being deployed and undeployed

=== Deploy example

This example shows a verticle deploying another verticle in several different ways including:

* Deploying without waiting for it to deploy
* Deploying and waiting for it to deploy
* Passing configuration to another verticle during deploy
* Deploying more than one instance
* Deploying as a worker verticle
* Undeploying a verticle deployment explicitly

link:src/main/java/io/vertx/example/core/verticle/deploy/DeployExample.java[Java verticle deployment example]
link:src/main/java/io/vertx/example/core/verticle/deploy/OtherVerticle.java[The verticle that will be deployed]

=== Asynchronous deployment example

This is similar to the deployment example, but it shows how the start and stop of a verticle can be asynchronous. This
is useful if the verticle has some startup or cleanup to do that takes some time, and we wish to avoid blocking the
an event loop.

link:src/main/java/io/vertx/example/core/verticle/asyncstart/DeployExample.java[Java verticle deployment example]
link:src/main/java/io/vertx/example/core/verticle/asyncstart/OtherVerticle.java[The verticle that will be deployed]

== Execute blocking example

This example demonstrates how you can include blocking code in with your non blocking code in a way that doesn't
block an event loop:

link:src/main/java/io/vertx/example/core/execblocking/ExecBlockingExample.java[Java execute blocking code example]

Run the example then open a browser and point it at link:http://localhost:8080[]





























