= Vert.x Mail examples

Here you'll find some examples how to use Vert.x mail-service to send mails
to a SMTP server either from the local machine or via the event bus on another
machine.

The examples use a few different configs

== link:src/main/java/io/vertx/example/mail/MailLocalhost.java[MailLocalhost]

Send a mail to localhost:25, e.g. to postfix running on the local machine

== link:src/main/java/io/vertx/example/mail/MailLogin.java[MailLogin]

Send a mail to an external smtp server (e.g. googlemail, sendgrid, aol etc)
requiring a login and enforcing use of TLS. The operation will fail if either
the account is not set or the server doesn't announce STARTTLS capability.

The login will currently use CRAM-MD5, PLAIN and LOGIN in the order of
preference, if the server announces AUTH but you don't need it (e.g. if you are
authenticated by a local ip address, turn login off with LoginOptions.DISABLE)

== link:src/main/java/io/vertx/example/mail/MailEB.java[MailEB]

Send a mail via the event bus to another vert.x instance registered as
vertx.mail. This will use the config set by the service and doesn't use a local
config object.

This example shows how to leave out the From address in a mail but setting
the bounceAddress property instead.

The service listening on the event bus can be started with

    vertx run service:io.vertx.mail-service

and vertx will pick up the package from maven and start it with default config.

== link:src/main/java/io/vertx/example/mail/MailPregen.java[MailPregen]

Send a mail that has been generated by another method (e.g. javamail).

This should enable supporting features not handled by the internal MIME
generator in mail-service. In this case no modifications of the mail text will
be done and the from and to headers are not evaluated. Please note that this
does not check if the mail is in a correct format and will send anything to the
SMTP server. For example if the mail text uses 8 bit chars or 8 bit header
lines, but the server doesn't support it the mail may probably fail.

This test uses a SSL connect to the mail server using Port 465 (which is
actually deprecated, but is still support by many mail servers e.g. googlemail
and AOL support port 465). The preferred way to send secure mails is TLS
required and port 587.
