= Vert.x Redis Client examples

Here you will find examples demonstrating the usage of the Vert.x Redis Client.

The example is available in several languages:

* Java: link:src/main/java/io/vertx/examples/redis/RedisClientVerticle.java[RedisClientVerticle.java]
* JavaScript: link:src/main/js/io/vertx/examples/redis/redis_client_verticle.js[redis_client_verticle.js]
* Groovy: link:src/main/groovy/io/vertx/examples/redis/redis_client_verticle.groovy[redis_client_verticle.groovy]
* Ruby: link:src/main/rb/io/vertx/examples/redis/redis_client_verticle.rb[redis_client_verticle.rb]

To run this example, you need a running Redis instance. Once running, you can configure the
verticles with the redis host:

----
{
    "host": "192.168.59.103"
}
----

By default it uses `127.0.0.1` as host. The post is set to `6379`.

Once the redis instance is running, you can launch it using:

----
# mandatory, it copies the vertx-redis-client
mvn clean package

# java
vertx run io.vertx.examples.redis.RedisClientVerticle -cp target/redis-examples-3.1.0-SNAPSHOT.jar -conf my-redis-config.json

# javascript
vertx run src/main/js/io/vertx/examples/redis/redis_client_verticle.js  -cp target/redis-examples-3.1.0-SNAPSHOT.jar -conf my-redis-config.json

# groovy
vertx run src/main/groovy/io/vertx/examples/redis/redis_client_verticle.groovy   -cp target/redis-examples-3.1.0-SNAPSHOT.jar -conf my-redis-config.json

# ruby
vertx run src/main/rb/io/vertx/examples/redis/redis_client_verticle.rb   -cp target/redis-examples-3.1.0-SNAPSHOT.jar -conf my-redis-config.json
----

