= Vert.x OpenShift (v2) Examples

This project shows how to deploy a Vert.x 3 applications to OpenShift V2. The same application is deployed using the two proposed approaches:

* using the quickstart based on the Do-It-Yourself cartridge (low level integration, without scalability support)
* using the vert.x 3 cartridge

This project is just an example of the structure and is not directly deployable oon OpenShift. You needs to log in on OpenShift and create the application with. Follows the provided guides:

* https://github.com/vert-x3/vertx-openshift-diy-quickstart[Tutorial to use the quickstart approach]
* https://github.com/vert-x3/vertx-openshift-cartridge[Tutorial to use the vert.x 3 cartridge]

== The application

The application is very simple and just creates a HTTP server. Notice that the application listens on a host and port accessible from the system properties. Openshift requires the application to be bound to this address and port.

link:src/main/java/io/vertx/example/HelloWorldVerticle.java[Vert.x verticle for OpenShift]

== The DIY version

This version uses the Do-It-Yourself cartridge. It's a low level integration, and it does not support (Openshift) scalability. The application _fat jar_ is placed into the `application` directory. The provided _action hooks_ manages the installation, start and stop of the application:

link:quickstart-diy/.openshift/action_hooks[The scripts]

== The cartridge version

This version uses the Vert.x 3 cartridge. It's a higher level integration, and it does support (Openshift) scalability. The application _fat jar_ is placed into the `application` directory. Additional configuration can be placed in the `configuration` directory.










