= Vert.x SQL Client examples

Here you will find examples demonstrating the usage of the Vert.x SQL Client.

== Simple

This example shows the basic functionality of the SQL client, it demonstrates how to connect to a database, perform
basic data definition queries by creating a test table plus test data, after it shows how to perform simple queries
without parameters and shows how to close the connection.

The example is available in several languages:

* Java: link:src/main/java/io/vertx/example/sqlclient/simple/SqlClientExample.java[SqlClientExample.java]
* Kotlin: link:src/main/kotlin/io/vertx/example/sqlclient/simple/SqlClientExample.kt[SqlClientExample.kt]
* Groovy: link:src/main/groovy/io/vertx/example/sqlclient/simple/sql_client_example.groovy[sql_client_example.groovy]

== Query Params

This is a follow up to the `Simple` example. In this example you will see how to write queries with parameters, the
advantage of doing so is to avoid common SQL injection security issues since all parameters are used in a
`PreparedStatement` before being sent to the database engine.

The example is available in several languages:

* Java: link:src/main/java/io/vertx/example/sqlclient/query_params/SqlClientExample.java[SqlClientExample.java]
* Kotlin: link:src/main/kotlin/io/vertx/example/sqlclient/query_params/SqlClientExample.kt[SqlClientExample.kt]
* Groovy: link:src/main/groovy/io/vertx/example/sqlclient/query_params/sql_client_example.groovy[sql_client_example.groovy]

== Transaction

The Transaction example show how to execute queries with a transaction using the asynchronous SQL client.

The example is available in several languages:

* link:src/main/java/io/vertx/example/sqlclient/transaction/SqlClientExample.java[SqlClientExample.java]
* Kotlin: link:src/main/kotlin/io/vertx/example/sqlclient/transaction/SqlClientExample.kt[SqlClientExample.kt]
* Groovy: link:src/main/groovy/io/vertx/example/sqlclient/transaction/sql_client_example.groovy[sql_client_example.groovy]

== Transaction Rollback

The Transaction rollback example is a modified version of the simple Transaction example.
In this example, we manage the transaction manually and, after inserting data, we rollback the changes.
The result should be an empty list.

The example is available in several languages:

* link:src/main/java/io/vertx/example/sqlclient/transaction_rollback/SqlClientExample.java[SqlClientExample.java]
* Kotlin: link:src/main/kotlin/io/vertx/example/sqlclient/transaction_rollback/SqlClientExample.kt[SqlClientExample.kt]
* Groovy: link:src/main/groovy/io/vertx/example/sqlclient/transaction_rollback/sql_client_example.groovy[sql_client_example.groovy]
