= Vert.x Infinispan examples

This project shows a simple example using the Infinispan cluster manager (instead of the Hazelcast cluster manager).

This project is composed by three small applications:

* link:src/main/java/io/vertx/example/infinispan/StatsProducerApp.java[Stats Producer App] - sending stats data on the event bus
* link:src/main/java/io/vertx/example/infinispan/StatsConsumerApp.java[Stats Consumer App] - consumes stats data from the
event bus, adds the value to the global stats counter
* link:src/main/java/io/vertx/example/infinispan/DisplayStatsApp.java[Display Stats App] - displays the value of the global
stats periodically

Start these applications from your IDE, and you should see the sent and receive data (don't forget to start the 3 of them
application).

You can start more than one StatsConsumerApp and see how the counter is incremented atomically


== Network interface selection

The applications try to pick the network address automatically, but it may be wrong. In this case pass the IP of the
interface you want to use as parameter.

== Launching the example from the command line

you can launch the producer and consumer as follows:

----
mvn clean package
java -jar target/infinispan-examples-3.6.0.CR2-fat.jar run io.vertx.example.infinispan.StatsProducerApp -cluster
java -jar target/infinispan-examples-3.6.0.CR2-fat.jar run io.vertx.example.infinispan.StatsConsumerApp -cluster
java -jar target/infinispan-examples-3.6.0.CR2-fat.jar run io.vertx.example.infinispan.DisplayStatsApp -cluster
----
