= Vert.x Ignite examples

This project shows a simple example using the cluster manager based on Apache Ignite (instead of the Hazelcast cluster
manager).

This project is composed by two small applications:

* link:src/main/java/io/vertx/example/ignite/ProducerApp.java[Producer App] - sending data on the event bus
* link:src/main/java/io/vertx/example/ignite/ConsumerApp.java[Consumer App] - receiving data from the event bus

Starts these applications from your IDE, and you should see the sent and receive data (don't forget to start both
application).

== Network interface selection

The applications try to pick the network address automatically, but it may be wrong. In this case pass the IP of the
interface you want to use as parameter.

This example uses the default member discovery (using multicast). Check the documentation for further details.

== Running from Maven

You can run this example as follows:

In a terminal, launch:

----
mvn compile exec:exec@producer
----

In another terminal, launch:

----
mvn compile exec:exec@consumer
----