= Vert.x Docker Examples

Here you will find examples demonstrating how to run Vert.x applications in Docker container. To run these examples you need https://www.docker.com/[Docker] installed on your computer. More details about these examples are in the http://vert-x3.github.io/docs/vertx-docker/[Vert.x Docker Manual].

== vertx-docker-java

This example deploys a Java verticle inside Docker.

The link:vertx-docker-java

To build and run it:
----
docker build -t sample/vertx-java .
docker run -t -i -p 8080:8080 sample/vertx-java
----

== vertx-docker-groovy

This example deploys a Groovy verticle inside Docker.

The link:vertx-docker-groovy

To build and run it:
----
docker build -t sample/vertx-groovy .
docker run -t -i -p 8080:8080 sample/vertx-groovy
----

== vertx-docker-example

This example builds and deploys a Java verticle inside Docker using Apache Maven

The link:vertx-docker-example

To build and run it:
----
mvn clean package docker:build
docker run -t -i -p 8080:8080 vertx/vertx3-example
----

== vertx-docker-java-fatjar

This example deploys a Java verticle inside Docker. The verticle is packaged as a _fat jar_.

The link:vertx-docker-java-fatjar

To build and run it:
----
docker build -t sample/vertx-java-fat .
docker run -t -i -p 8080:8080 sample/vertx-java-fat
----
